name: app
description: Dana Health.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.6+987

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #facebook prefered link
  flutter_facebook_app_links:
   git: https://github.com/vatsanatech/flutter_facebook_app_links
  # Translations
  intl_utils: ^2.4.0 # To regenerate the intl files with the terminal instead of the IntelliJ plugin
  package_info_plus: ^3.0.3
  #responsive
  flutter_screenutil: ^5.7.0
  # Firebase
  firebase_core: ^2.5.0
  cloud_firestore: ^4.3.2
  firebase_storage: ^11.0.11
  firebase_analytics: ^10.1.1
  firebase_auth: ^4.2.6
  firebase_crashlytics: ^3.0.12
  firebase_remote_config: ^3.0.6

  #http call
  http: ^0.13.6

  # Auth
  google_sign_in: ^5.0.7
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.1
  flutter_facebook_auth: ^5.0.7

  #Arch
  flutter_bloc: ^8.1.1
  rxdart: ^0.27.1
  get_it: ^7.2.0

  # Utils
  flutter_svg_provider: ^0.1.9
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^0.23.0+1
  shared_preferences: ^2.0.15
  animations: ^2.0.1
  google_fonts: ^4.0.3
  flutter_signin_button: ^2.0.0
  flutter_html: ^2.2.1
  wheel_chooser: ^1.0.0
  flutter_rating_bar: ^4.0.1
  transparent_image: ^2.0.0
  share_plus: ^6.3.1
  url_launcher: ^6.1.3
  week_of_year: ^2.0.0
  # https://pub.dev/packages/lazy_load_scrollview/install
  lazy_load_scrollview: ^1.3.0
  purchases_flutter: ^4.5.2
  version: ^3.0.0
  simple_progress_indicators: ^0.2.0
  in_app_review: ^2.0.6
  flutter_app_badger: ^1.5.0
  uni_links: ^0.5.1
  dartz: ^0.10.1
  #Graphics
  fl_chart: ^0.62.0

  #Models
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  freezed: ^2.2.0
  mocktail: ^0.3.0
  #better test package
  mockito: ^5.4.0
  bloc_test: ^9.1.0
  #Audio player
  just_audio: ^0.9.30
  audio_session: ^0.1.13
  audio_service: ^0.18.9

  appsflyer_sdk: 6.9.3 # To track app installations and their business performance
  cupertino_icons: ^1.0.5

  #counrty codes
  country_codes: ^2.2.0

  #push notifications
  onesignal_flutter: ^3.5.0
  timeago: ^3.2.2
  mixpanel_flutter: ^1.5.1
  collection: ^1.15.0-nullsafety.4
  go_router: ^5.1.0
  firebase_dynamic_links: ^5.0.7
  formz: ^0.4.1
  freezed_annotation: ^2.2.0
  carousel_slider: ^4.2.1
  very_good_infinite_list: ^0.7.0
  permission_handler: ^10.2.0
dev_dependencies:
  build_runner:
  flutter_native_splash: ^2.2.0+1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  # generate: true
  uses-material-design: true

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont-wght.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

  assets:
    - assets/images/
    - assets/images/weeks/
    - assets/images/dialogs/

flutter_intl:
  enabled: true
